/**
 * Feature keys estándar del sistema Avax Health.
 * Usar estas constantes en @RequireFeature() y en la configuración de planes.
 */
export const FEATURES = {
  WHATSAPP_AGENT: 'whatsapp_agent',
  WHATSAPP_REMINDERS: 'whatsapp_reminders',
  MULTI_CONSULTORIO: 'multi_consultorio',
  ADVANCED_REPORTS: 'advanced_reports',
  CSV_EXPORT: 'csv_export',
  CUSTOM_BRANDING: 'custom_branding',
  API_ACCESS: 'api_access',
  AUDIT_LOGS: 'audit_logs',
  PRIORITY_SUPPORT: 'priority_support',
  INVENTARIO: 'inventario',
  PAGOS: 'pagos',
  PROVEEDORES: 'proveedores',
  MULTI_SUCURSAL: 'multi_sucursal',
} as const;

export type FeatureKey = (typeof FEATURES)[keyof typeof FEATURES];

/** Labels legibles para cada feature (para mostrar en landing / admin) */
export const FEATURE_LABELS: Record<string, string> = {
  whatsapp_agent: 'WhatsApp + IA',
  whatsapp_reminders: 'Recordatorios WhatsApp',
  multi_consultorio: 'Multi-Consultorio',
  advanced_reports: 'Reportes Avanzados',
  csv_export: 'Exportación CSV',
  custom_branding: 'Branding Personalizado',
  api_access: 'Acceso API',
  audit_logs: 'Registro de Auditoría',
  priority_support: 'Soporte Prioritario',
  inventario: 'Inventario',
  pagos: 'Gestión de Pagos',
  proveedores: 'Proveedores',
  multi_sucursal: 'Multi-Sucursal',
};

const ALL_FALSE: Record<string, boolean> = {
  whatsapp_agent: false,
  whatsapp_reminders: false,
  multi_consultorio: false,
  advanced_reports: false,
  csv_export: false,
  custom_branding: false,
  api_access: false,
  audit_logs: false,
  priority_support: false,
  inventario: false,
  pagos: false,
  proveedores: false,
  multi_sucursal: false,
};

/**
 * 5 planes Avax Health: Trial (gratis) + 4 pagos.
 * Referencia para seed/migración de datos.
 */
export const PLAN_TEMPLATES = {
  TRIAL: {
    nombre: 'Trial Gratuito',
    descripcion: 'Probá Avax Health gratis durante 14 días con funciones básicas.',
    precio_mensual: 0,
    max_usuarios: 2,
    max_pacientes: 50,
    is_highlighted: false,
    is_default_trial: true,
    orden: 0,
    features: {
      ...ALL_FALSE,
      csv_export: true,
      inventario: true,
      pagos: true,
    },
  },
  CONSULTORIO_STANDARD: {
    nombre: 'Avax Consultorio Standard',
    descripcion: 'Ideal para consultorios pequeños que buscan digitalizar su gestión.',
    precio_mensual: 4990,
    max_usuarios: 3,
    max_pacientes: 500,
    is_highlighted: false,
    is_default_trial: false,
    orden: 1,
    features: {
      ...ALL_FALSE,
      whatsapp_reminders: true,
      csv_export: true,
      inventario: true,
      pagos: true,
      proveedores: true,
    },
  },
  CONSULTORIO_PLUS_IA: {
    nombre: 'Avax Consultorio Plus IA',
    descripcion: 'Potenciá tu consultorio con inteligencia artificial y automatizaciones.',
    precio_mensual: 9990,
    max_usuarios: 5,
    max_pacientes: 2000,
    is_highlighted: false,
    is_default_trial: false,
    orden: 2,
    features: {
      ...ALL_FALSE,
      whatsapp_agent: true,
      whatsapp_reminders: true,
      advanced_reports: true,
      csv_export: true,
      custom_branding: true,
      audit_logs: true,
      inventario: true,
      pagos: true,
      proveedores: true,
    },
  },
  CLINICA_STANDARD: {
    nombre: 'Avax Clinica Standard',
    descripcion: 'Para clínicas con múltiples profesionales que necesitan escalar.',
    precio_mensual: 19990,
    max_usuarios: 15,
    max_pacientes: null,
    is_highlighted: true,
    is_default_trial: false,
    orden: 3,
    features: {
      ...ALL_FALSE,
      whatsapp_agent: true,
      whatsapp_reminders: true,
      multi_consultorio: true,
      advanced_reports: true,
      csv_export: true,
      custom_branding: true,
      api_access: true,
      audit_logs: true,
      inventario: true,
      pagos: true,
      proveedores: true,
    },
  },
  CLINICA_PLUS_IA: {
    nombre: 'Avax Clinica Plus IA',
    descripcion: 'La experiencia completa: todas las funciones, soporte prioritario y sin límites.',
    precio_mensual: 34990,
    max_usuarios: 50,
    max_pacientes: null,
    max_sucursales: null,
    is_highlighted: false,
    is_default_trial: false,
    orden: 4,
    features: {
      whatsapp_agent: true,
      whatsapp_reminders: true,
      multi_consultorio: true,
      advanced_reports: true,
      csv_export: true,
      custom_branding: true,
      api_access: true,
      audit_logs: true,
      priority_support: true,
      inventario: true,
      pagos: true,
      proveedores: true,
      multi_sucursal: false,
    },
  },
  CLINICA_PRO_IA: {
    nombre: 'Avax Clinica Pro IA',
    descripcion: 'Administrá múltiples clínicas y sucursales desde un solo lugar. Para redes de salud y grupos médicos.',
    precio_mensual: 59990,
    max_usuarios: 200,
    max_pacientes: null,
    max_sucursales: 10,
    is_highlighted: true,
    is_default_trial: false,
    orden: 5,
    features: {
      whatsapp_agent: true,
      whatsapp_reminders: true,
      multi_consultorio: true,
      advanced_reports: true,
      csv_export: true,
      custom_branding: true,
      api_access: true,
      audit_logs: true,
      priority_support: true,
      inventario: true,
      pagos: true,
      proveedores: true,
      multi_sucursal: true,
    },
  },
};
